# Generated by Django 5.2.17 on 2026-09-16 15:21

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Ejercicio",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=120)),
                ("descripcion", models.TextField(blank=True)),
                ("equipamiento", models.CharField(blank=True, max_length=120)),
                ("grupo_muscular", models.CharField(max_length=80)),
                ("activo", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["nombre"],
                "indexes": [
                    models.Index(
                        fields=["nombre"], name="tracker_eje_nombre_bbe355_idx"
                    ),
                    models.Index(
                        fields=["grupo_muscular"], name="tracker_eje_grupo_m_aeb37d_idx"
                    ),
                    models.Index(
                        fields=["activo"], name="tracker_eje_activo_5ea26d_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="Entrenamiento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=120)),
                ("descripcion", models.TextField(blank=True)),
                ("notas", models.TextField(blank=True)),
                ("fecha_creacion", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["nombre"],
                "indexes": [
                    models.Index(
                        fields=["nombre"], name="tracker_ent_nombre_14d8f1_idx"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="EntrenamientoEjercicio",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "orden",
                    models.PositiveIntegerField(
                        validators=[django.core.validators.MinValueValidator(1)]
                    ),
                ),
                ("notas", models.TextField(blank=True)),
                (
                    "ejercicio",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="entrenamientos",
                        to="tracker.ejercicio",
                    ),
                ),
                (
                    "entrenamiento",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ejercicios",
                        to="tracker.entrenamiento",
                    ),
                ),
            ],
            options={
                "ordering": ["orden"],
            },
        ),
        migrations.CreateModel(
            name="Usuario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=120)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("fecha_registro", models.DateTimeField(auto_now_add=True)),
                ("activo", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["nombre"],
                "indexes": [
                    models.Index(
                        fields=["nombre"], name="tracker_usu_nombre_884f0d_idx"
                    ),
                    models.Index(
                        fields=["activo"], name="tracker_usu_activo_14f09e_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="UsuarioEntrenamiento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha_asignacion", models.DateTimeField(auto_now_add=True)),
                (
                    "entrenamiento",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="usuarios",
                        to="tracker.entrenamiento",
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="entrenamientos",
                        to="tracker.usuario",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SesionEntrenamiento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha", models.DateTimeField()),
                ("notas", models.TextField(blank=True)),
                (
                    "usuario_entrenamiento",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sesiones",
                        to="tracker.usuarioentrenamiento",
                    ),
                ),
            ],
            options={
                "ordering": ["-fecha"],
            },
        ),
        migrations.CreateModel(
            name="UsuarioEntrenamientoEjercicio",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("notas", models.TextField(blank=True)),
                (
                    "entrenamiento_ejercicio",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="elecciones",
                        to="tracker.entrenamientoejercicio",
                    ),
                ),
                (
                    "usuario_entrenamiento",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ejercicios_elegidos",
                        to="tracker.usuarioentrenamiento",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Serie",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "numero_serie",
                    models.PositiveIntegerField(
                        validators=[django.core.validators.MinValueValidator(1)]
                    ),
                ),
                (
                    "repeticiones",
                    models.PositiveIntegerField(
                        validators=[django.core.validators.MinValueValidator(1)]
                    ),
                ),
                (
                    "peso",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=7,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                ("notas", models.TextField(blank=True)),
                (
                    "sesion_entrenamiento",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="series",
                        to="tracker.sesionentrenamiento",
                    ),
                ),
                (
                    "usuario_entrenamiento_ejercicio",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="series",
                        to="tracker.usuarioentrenamientoejercicio",
                    ),
                ),
            ],
            options={
                "ordering": ["numero_serie"],
            },
        ),
        migrations.AddIndex(
            model_name="entrenamientoejercicio",
            index=models.Index(
                fields=["entrenamiento"], name="tracker_ent_entrena_316f8f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="entrenamientoejercicio",
            index=models.Index(
                fields=["ejercicio"], name="tracker_ent_ejercic_922e88_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="entrenamientoejercicio",
            constraint=models.UniqueConstraint(
                fields=("entrenamiento", "ejercicio"),
                name="unique_entrenamiento_ejercicio",
            ),
        ),
        migrations.AddConstraint(
            model_name="entrenamientoejercicio",
            constraint=models.UniqueConstraint(
                fields=("entrenamiento", "orden"), name="unique_entrenamiento_orden"
            ),
        ),
        migrations.AddIndex(
            model_name="usuarioentrenamiento",
            index=models.Index(
                fields=["usuario"], name="tracker_usu_usuario_a65fdd_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="usuarioentrenamiento",
            index=models.Index(
                fields=["entrenamiento"], name="tracker_usu_entrena_9fcf6f_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="usuarioentrenamiento",
            constraint=models.UniqueConstraint(
                fields=("usuario", "entrenamiento"), name="unique_usuario_entrenamiento"
            ),
        ),
        migrations.AddIndex(
            model_name="sesionentrenamiento",
            index=models.Index(
                fields=["usuario_entrenamiento", "-fecha"],
                name="tracker_ses_usuario_92dfff_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="usuarioentrenamientoejercicio",
            index=models.Index(
                fields=["usuario_entrenamiento"], name="tracker_usu_usuario_c7c551_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="usuarioentrenamientoejercicio",
            index=models.Index(
                fields=["entrenamiento_ejercicio"],
                name="tracker_usu_entrena_a8471b_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="usuarioentrenamientoejercicio",
            constraint=models.UniqueConstraint(
                fields=("usuario_entrenamiento", "entrenamiento_ejercicio"),
                name="unique_usuario_entrenamiento_ejercicio",
            ),
        ),
        migrations.AddIndex(
            model_name="serie",
            index=models.Index(
                fields=["sesion_entrenamiento"], name="tracker_ser_sesion__59c34d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="serie",
            index=models.Index(
                fields=["usuario_entrenamiento_ejercicio"],
                name="tracker_ser_usuario_399409_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="serie",
            constraint=models.UniqueConstraint(
                fields=(
                    "sesion_entrenamiento",
                    "usuario_entrenamiento_ejercicio",
                    "numero_serie",
                ),
                name="unique_serie_en_sesion",
            ),
        ),
    ]
